//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsvHelperIssueDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsvHelperIssueDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column1,Column2,Column3
        ///1,1,1
        ///2,2,2
        ///3,3,3
        ///4,4,4
        ///5,5,5
        ///6,6,6
        ///7,7,7
        ///8,8,8
        ///9,9,9
        ///10,10,10
        ///11,11,11
        ///12,12,12
        ///13,13,13
        ///14,14,14
        ///15,15,15
        ///16,16,16
        ///17,17,17
        ///18,18,18
        ///19,19,19
        ///20,20,20
        ///21,21,21
        ///22,22,22
        ///23,23,23
        ///24,24,24
        ///25,25,25
        ///26,26,26
        ///27,27,27
        ///28,28,28
        ///29,29,29
        ///30,30,30
        ///31,31,31
        ///32,32,32
        ///33,33,33
        ///34,34,34
        ///35,35,35
        ///36,36,36
        ///37,37,37
        ///38,38,38
        ///39,39,39
        ///40,40,40
        ///41,41,41
        ///42,42,42
        ///43,43,43
        ///44,44,44
        ///45,45,45.
        /// </summary>
        internal static string sample_data {
            get {
                return ResourceManager.GetString("sample_data", resourceCulture);
            }
        }
    }
}
